video(ocl): enable cl_khr_subgroups extension in dis_flow.cl
When running DIS Optical Flow on OpenCL devices supporting `cl_khr_subgroups` (such as ARM Mali GPUs), `dis_flow.cpp` detects subgroup support and appends `-DCV_USE_SUBGROUPS=1` to OpenCL kernel build options.

However, `modules/video/src/opencl/dis_flow.cl` was missing `#pragma OPENCL EXTENSION cl_khr_subgroups : enable`. As a result, OpenCL kernel compilation failed with implicit function declaration errors:

    <source>:189:12: error: implicit declaration of function 'sub_group_reduce_add' is invalid in OpenCL
    sum_diff = sub_group_reduce_add(sum_diff);
               ^
    <source>:229:11: error: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
    int sid = get_sub_group_local_id();

Fix by adding `#pragma OPENCL EXTENSION cl_khr_subgroups : enable` inside `#ifdef CV_USE_SUBGROUPS` in `dis_flow.cl`.

Fixes #27507