MGS-8318 [#ccc] Fix error:implicit declaration of function 'sub_group_reduce_add' is invalid in OpenCL.
The OpenCL extension cl_khr_subgroups is not supported in OpenCL 1.2.

This feature requires at least OpenCL 2.0 or higher. By default, the C++ C language standard used

is C++ C 1.2. Therefore, specify OpenCL version to 3.0 in the build-options.

Signed-off-by: jiajia Qian <jiajia.qian@nxp.com>