Remove <cstdint> include
To avoid the following error (linux x64):
  from /build/precommit_linux64/3.4/opencv/modules/imgcodecs/src/
        grfmt_tiff.cpp:54:
  /usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error
    This file requires compiler and library support for the ISO C++
    2011 standard. This support is currently experimental, and must be
    enabled with the -std=c++11 or -std=gnu++11 compiler options.