Merge pull request #27242 from mshabunin:fix-uwp-build
Looks like UWP builds were broken on 5.x:
```
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,33): error C3646: 'size': unknown override specifier (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,37): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,33): error C3646: 'size': unknown override specifier (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\videoio_registry.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,37): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\videoio_registry.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,33): error C3646: 'size': unknown override specifier (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_bridge.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_capture.hpp(65,37): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\GHA-OCV-6\_work\opencv\opencv\opencv\modules\videoio\src\cap_winrt_bridge.cpp) [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [C:\GHA-OCV-6\_work\opencv\opencv\build\modules\videoio\opencv_videoio.vcxproj]
```

Notes:

- Pipeline passes even though there are errors in the build
- I decided to remove _highgui_ WinRT backend, because it uses C-API which is has been removed in 5.x. I believe nobody uses it anyway.
- Change in anneal library is caused by the issue in WinAPI header - it does not declare two functions for UWP, even though documentation states compatibility. See also https://github.com/openssl/openssl/pull/18311
  https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtuallock

  > Minimum supported client	Windows XP [desktop apps | UWP apps]
  > Minimum supported server	Windows Server 2003 [desktop apps | UWP apps]